import os
import google.generativeai as genai
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from dotenv import load_dotenv

# 1. Setup
load_dotenv()
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))


def generate_chapter(title, requirements):
    """Generates a long, detailed chapter using Gemini."""
    print(f"Writing Chapter: {title}...")
    model = genai.GenerativeModel("gemini-2.5-pro")

    prompt = f"""
    Write a detailed, formal security policy chapter titled '{title}'.
    
    CRITICAL REQUIREMENTS TO INCLUDE (Do not change the logic):
    {requirements}
    
    INSTRUCTIONS:
    - Write at least 400-500 words for this chapter.
    - Use formal compliance language (e.g., "Must", "Mandatory", "Strictly Prohibited").
    - Invent 'filler' details about version numbers, audit logs, and compliance officers to make it long.
    - Structure it with sub-headers like '1.1 Purpose', '1.2 Scope', '1.3 Technical Controls'.
    - Do NOT use markdown. Just plain text.
    """
    return model.generate_content(prompt).text


def create_big_pdf():
    # Define Sections
    chapters = [
        ("1.0 Identity & Access Management (IAM)",
         "- MFA is mandatory for all human users.\n- Root account usage is prohibited.\n- Keys must be rotated every 90 days."),

        ("2.0 Object Storage (S3)",
         "- All Production buckets must have Versioning ENABLED.\n- Public Access must be BLOCKED (True).\n- Encryption (AES-256) is required."),

        ("3.0 Compute Security (EC2)",
         "- Port 22 (SSH) must strictly be closed to the public internet (0.0.0.0/0).\n- Bastion hosts must be used."),

        ("4.0 Database Security (RDS)",
         "- Databases must not have PubliclyAccessible=True.\n- Backups must be retained for 30 days."),

        ("5.0 Network Security (VPC)",
         "- Default Security Groups must deny all traffic by default.\n- Flow Logs must be enabled.")
    ]

    # Setup PDF
    base_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(base_dir, "backend", "data",
                             "acme_global_security_policy_v3.pdf")
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title Page
    story.append(
        Paragraph("ACME Global Security Standard v3.0", styles['Title']))
    story.append(
        Paragraph("Confidential - Internal Use Only", styles['Heading2']))
    story.append(Spacer(1, 24))
    story.append(
        Paragraph("Generated by Gemini Reasoning Engine", styles['Italic']))
    story.append(PageBreak())

    # Generate Content
    for title, reqs in chapters:
        # Header
        story.append(Paragraph(title, styles['Heading1']))
        story.append(Spacer(1, 12))

        # AI Text
        text = generate_chapter(title, reqs)

        # Clean up text and add to PDF
        for paragraph in text.split('\n'):
            if paragraph.strip():
                story.append(Paragraph(paragraph.strip(), styles['BodyText']))
                story.append(Spacer(1, 8))

        story.append(PageBreak())

    doc.build(story)
    print(f" PDF Generated: {file_path}")


if __name__ == "__main__":
    create_big_pdf()
